const openings = [
    "Buongiornissimo",
    "Buondì",
    "Buongiorgioo",
    "Buondìììì",
    "Buongiornissimooo",
    "Salve",
    "Buoooondì",
    "Buooongiorgio",
    "Buongiorno"
]

const tags = [
    "friends", 
    "dogs",
    "angry",
    "the office",
    "the office dwight",
    "michael scott",
    "cringe",
    "adorable",
    "animale",
    "tired",
    "sleepy",
    "rene ferretti",
    "cheer",
    "cat",
    "friends tv",
    "chandler",
    "ross geller",
    "monica geller",
    "rechael green",
    "joey tribbiani",
    "dance",
    "reaction",
    "can do it",
    "full",
    "relaxing",
    "mad",
    "late",
    "grinch",
    "stress",
    "theboys",
    "crying",
    "party",
    "excited",
    "fabolous",
    "not happy",
    "working",
    "hello",
    "yay",
    "himym",
    "big bang theory",
    "mr bean",
    "corgi"
]

export {openings, tags}